### ISSUE TITLE
❌ Error orrurred: Response code not 200. Response Status is 403

### ISSUE THREAD

**Issue by Shjpr9** [ciuzaak/Claude-Telegram-Bot#18]
Hey there. I have run the bot but I got the following error:
❌ Error orrurred: Response code not 200. Response Status is 403. /reset

This is how I set my config.yml file:
```
telegram:
  bot_token: MY-BOT-TOKEN
  user_ids: [123456789, 987654321]
claude:
  api: # leave it blank if you don't want to use claude
bard:
  api: ZAjHY4Pn_SOMEVALUEwFEw., sidts-SOMEVALUE_LXGRmuSA
```

As the format says 
- __Secure-1PSID, __Secure-1PSIDTS

This is exactly how I did it but it does not work. 
Thanks for your time
